server:
  port: 8761
spring:
  application:
    name: server-center
eureka:
  client:
    fetch-registry: false                 #关闭检索服务
    register-with-eureka: false           #关闭自己自己注册
  server:
    enable-self-preservation: false       #关闭自我保护
    eviction-interval-timer-in-ms:  5000  #清理无效的时间间隔
  instance:
    lease-renewal-interval-in-seconds: 10 #租期更新时间
    lease-expiration-duration-in-seconds: 30  #租期到期时间（默认90秒）  这样可以防止因保护模式而不将挂掉的服务剔除